lib/core/application/auth/auth_bloc.dart
lib/core/oauth.dart
lib/core/service/auth/auth_service.dart

- Use token from storage when doing logout 
- If endSession request fail, still attempt to clear all token saved in storage and logout

enhance logout flow

---

lib/core/data/user/dtos/user_query.dart
lib/core/data/user/user_repository_impl.dart

- use getMe to query current logged in user instead of getUser

fix(gql): use getMe instead of getUser to query current logged in user

---

codemagic.yaml

- Adjust codemagic for build staging

Adjust codemagic for build staging

---

codemagic.yaml

Setup CI/CD build android

---

lib/core/application/auth/auth_bloc.dart
lib/core/application/auth/auth_bloc.freezed.dart
lib/core/oauth.dart
lib/core/presentation/pages/profile/views/tabs/profile_info_tab_view.dart
lib/core/service/auth/auth_service.dart
lib/injection/register_module.config.dart

- Apply declarative approach for auth flow 
- AuthBloc will listen for oauth token state change and emit authentication state of UI 
- create tokenStateStream controller in AppOAuth, everytime token state is change(token valid or invalid due to expiration or logout), tokenState is updated and notify the subscriber (here is AuthBloc)
- AuthBloc will base on tokenState to handle auth logic for UI

enhance(auth): convert from imperative to declarative app auth flow

---

lib/core/presentation/widgets/bottom_bar_widget.dart

- Make bottom bar item easier to tap

enhance(ui): make bottom bar item easy to tap

---

android/app/build.gradle
codemagic.yaml

- Update CI/CD for signed app and automate upload to Play Console

Update CI/CD for signed app

---

codemagic.yaml

- Whenever push on some branch `release/*` pattern -> Will trigger build iOS Production & Android production, then it'll automate upload to AppStore/PlayStore

Setup CI/CD for release flow

---

ios/Podfile.lock

Fix Podfile lock

---

codemagic.yaml
ios/Podfile.lock
pubspec.lock
pubspec.yaml

- Increase firebase core version

Fix firebase core pod

---

lib/core/presentation/pages/profile/views/tabs/profile_info_tab_view.dart
lib/core/presentation/pages/profile/widgets/profile_page_header_widget.dart

- Fix overflow text in profile page

fix(ui) fix overflow text in profile page

---

android/app/src/production/google-services.json
android/app/src/staging/google-services.json
ios/config/production/GoogleService-Info.plist
lib/firebase_options_production.dart
lib/firebase_options_staging.dart

Adjust firebase api key

---

codemagic.yaml
pubspec.yaml

- Trigger release flow when create tag
- Adjust build number in CI-CD flow

Improve codemagic script

---

.gitignore
README.md
android/app/build.gradle

- Configure debug sign on Android platform

Configure debug sign on Android platform

---

lib/core/presentation/pages/chat/chat_detail/chat_detail_page.dart
lib/core/presentation/pages/chat/chat_list/chat_list_page.dart
lib/core/presentation/pages/chat/chat_setting/chat_setting_page.dart
lib/core/presentation/pages/chat/chat_stack_page.dart
lib/core/presentation/pages/event/events_listing_page.dart
lib/router/app_router.dart
lib/router/app_router.gr.dart

- Define basic chat routing flow

feat(chat): define chat routing flow

---

lib/app.dart
lib/core/presentation/pages/home/home_page.dart
lib/core/service/firebase/firebase_service.dart
lib/core/service/shake/shake_service.dart
lib/injection/register_module.config.dart
lib/router/app_router.gr.dart

Refactor shake service

---

lib/core/service/shake/shake_service.dart

Fix shake handle

---

lib/core/application/chat/chat_list_bloc/chat_list_bloc.dart
lib/core/application/chat/chat_list_bloc/chat_list_bloc.freezed.dart
lib/core/domain/chat/chat_enums.dart
lib/core/presentation/pages/chat/chat_list/chat_list_page.dart
lib/core/presentation/pages/chat/chat_list/views/chat_list_page_view.dart
lib/core/presentation/pages/chat/chat_list/widgets/channel_list_item.dart
lib/core/presentation/pages/chat/chat_list/widgets/direct_message_item.dart
lib/core/presentation/pages/chat/chat_list/widgets/unseen_message_count_widget.dart
lib/core/presentation/pages/chat/chat_stack_page.dart
lib/core/presentation/widgets/chat/matrix_avatar.dart
lib/core/presentation/widgets/chat/mxc_image.dart
lib/core/presentation/widgets/common/appbar/lemon_appbar_widget.dart
lib/core/utils/chat/matrix_file_extension.dart
lib/core/utils/chat/matrix_room_extension.dart
lib/core/utils/chat/matrix_string_color_extension.dart
lib/core/utils/stream_extension.dart
lib/i18n/chat/chat_en.i18n.json
lib/i18n/i18n.g.dart

- Fetch matrix rooms and filter by groups, DM, unread DMs (following the UI)
- Please note that this chat list will change according to selected space on the right drawer

feat(chat): handle logic get matrix rooms

---

lib/core/application/chat/chat_list_bloc/chat_list_bloc.dart
lib/core/application/chat/chat_space_bloc/chat_space_bloc.dart
lib/core/application/chat/chat_space_bloc/chat_space_bloc.freezed.dart
lib/core/presentation/pages/chat/chat_list/chat_list_page.dart
lib/core/presentation/pages/chat/chat_list/views/chat_list_page_view.dart
lib/core/presentation/pages/chat/chat_list/widgets/direct_message_item.dart
lib/core/presentation/pages/chat/chat_stack_page.dart
lib/core/presentation/pages/home/home_page.dart
lib/core/presentation/widgets/chat/spaces_drawer.dart
lib/core/presentation/widgets/common/appbar/lemon_appbar_widget.dart
lib/core/service/matrix/matrix_chat_space_extension.dart
lib/core/service/matrix/matrix_service.dart
lib/i18n/chat/chat_en.i18n.json
lib/i18n/i18n.g.dart
lib/router/app_router.gr.dart

- Load available spaces from user's matrix account
- Load all rooms available in selected spaces

feat(chat): chat space

---

lib/core/presentation/pages/chat/chat_list/widgets/channel_list_item.dart
lib/core/presentation/pages/chat/chat_list/widgets/direct_message_item.dart
lib/core/presentation/pages/chat/chat_message/chat_message_page.dart
lib/core/presentation/pages/chat/chat_message/view/chat_message_view.dart
lib/core/presentation/pages/chat/chat_message/widgets/message_item/message_content_widget.dart
lib/core/presentation/pages/chat/chat_message/widgets/message_item/message_item_widget.dart
lib/core/presentation/pages/chat/chat_message/widgets/message_item/state_message_item_widget.dart
lib/core/presentation/pages/chat/chat_message/widgets/messages_list_widget.dart
lib/core/utils/chat/filter_event_timeline_extension.dart
lib/core/utils/chat/matrix_client_ios_badge_extension.dart
lib/core/utils/chat/matrix_date_time_extension.dart
lib/router/app_router.dart
lib/router/app_router.gr.dart
pubspec.lock
pubspec.yaml

- Implement logic load chat messages 
- Build simple UI render messages list and message item

feat(chat): chat messages

---

lib/core/presentation/pages/chat/chat_message/chat_message_page.dart
lib/core/presentation/pages/chat/chat_message/view/chat_message_view.dart
lib/core/presentation/pages/chat/chat_message/widgets/chat_input/reply_content_widget.dart
lib/core/presentation/pages/chat/chat_message/widgets/chat_input/reply_display_widget.dart
lib/core/presentation/pages/chat/chat_message/widgets/message_item/html_message_widget.dart
lib/core/presentation/pages/chat/chat_message/widgets/message_item/image_message_widget.dart
lib/core/presentation/pages/chat/chat_message/widgets/message_item/message_content_widget.dart
lib/core/presentation/pages/chat/chat_message/widgets/message_item/message_item_widget.dart
lib/core/presentation/pages/chat/chat_message/widgets/messages_list_widget.dart
lib/core/presentation/pages/chat/chat_stack_page.dart
lib/core/presentation/widgets/common/swipe/swipeable.dart
lib/core/presentation/widgets/hero_image_viewer_widget.dart
pubspec.lock
pubspec.yaml

- Implement reply message logic 
- Implement render image message

feat(chat-message) enhance chat message ui and logic

---

lib/app.dart
lib/theme/sizing.dart
lib/theme/spacing.dart
lib/theme/typo.dart
pubspec.lock
pubspec.yaml

- Add https://pub.dev/packages/flutter_screenutil to adapting screen and font size. Let your UI display a reasonable layout on different screen sizes!
- Currently only apply on Sizing, Typo and Spacing classes.

Enhance/responsive UI

---

pubspec.yaml

chore(deps): bump sliver version

---

lib/core/data/notification/dtos/notification_dtos.dart
lib/core/data/notification/dtos/notification_dtos.freezed.dart
lib/core/data/notification/dtos/notification_dtos.g.dart

fix(notification): notification entity

---

lib/core/presentation/pages/discover/discover_page/discover_page.dart
lib/core/presentation/pages/event/event_detail_page.dart
lib/core/presentation/pages/home/home_page.dart
lib/core/presentation/pages/home/views/list/home_newsfeed_list.dart
lib/core/presentation/pages/notification/notifications_listing_page.dart
lib/core/presentation/pages/profile/views/list/profile_posts_list_view.dart
lib/core/presentation/widgets/common/appbar/lemon_appbar_widget.dart
lib/core/presentation/widgets/common/appbar/profile_animated_appbar_widget.dart
lib/core/presentation/widgets/event/event_post_card_widget.dart
lib/core/presentation/widgets/post/post_profile_card_widget.dart

fix/polish UI

---

lib/core/presentation/pages/discover/discover_page/views/discover_upcoming_events.dart

- add missing navigation for upcoming events

fix(events): add navigation for upcoming events in discover screen

---

android/app/build.gradle

- fix(android): wrong manifest placeholder

fix(android): wrong manifest placeholder

---

lib/core/presentation/pages/home/home_page.dart
lib/core/presentation/widgets/bottom_bar/bottom_bar_widget.dart
lib/core/presentation/widgets/home/floating_create_button.dart

- fix: adjust position of floating button

fix: adjust position of floating button

---

lib/core/application/profile/user_profile_bloc/user_profile_bloc.dart
lib/core/domain/onboarding/onboarding_inputs.dart
lib/core/domain/onboarding/onboarding_inputs.freezed.dart
lib/core/domain/onboarding/onboarding_inputs.g.dart

- fix(profile): adjust from userId to id

fix(profile): adjust from userId to id

---

lib/core/presentation/widgets/common/button/linear_gradient_button_widget.dart

- Update linear gradient button style
- Make linear gradient worked with disabled mode

fix: linear gradient button

---

lib/app.dart
lib/core/presentation/pages/profile/views/tabs/profile_info_tab_view.dart

- Fix issue ui display incorrectly on ipad or tablet devices

fix(responsive ui): fix issue ui display incorrectly on ipad or tablet

---

lib/core/presentation/pages/event/guest_event_detail_page/widgets/guest_event_detail_hosts.dart

- Fix laggy when using BackdropFilter
- Use ImageFiltered instead

fix(ui): fix event host item laggy when using backdrop filter

---

lib/core/presentation/pages/chat/chat_list/widgets/chat_list_item.dart
lib/core/presentation/pages/chat/chat_message/view/chat_message_view.dart
lib/core/presentation/pages/home/home_page.dart
lib/core/presentation/pages/root/root_page.dart
lib/core/presentation/widgets/chat/matrix_avatar.dart
lib/core/presentation/widgets/future_loading_dialog.dart

- Implement auth check when try access chat page
- Fix UI for display wrong online badge 
- Add future_loading_dialog based from this package : [Link](https://pub.dev/packages/future_loading_dialog)
- Implement join room when got invite

feat/check auth chat & implement join chat room

---

lib/core/application/onboarding/onboarding_bloc/onboarding_bloc.dart
lib/core/application/onboarding/onboarding_bloc/onboarding_state.dart
lib/core/application/profile/edit_profile_bloc/edit_profile_bloc.dart
lib/core/application/profile/edit_profile_bloc/edit_profile_state.dart
lib/core/data/user/dtos/user_dtos.dart
lib/core/data/user/dtos/user_query.dart
lib/core/domain/common/common_enums.dart
lib/core/domain/onboarding/onboarding_inputs.dart
lib/core/domain/user/entities/user.dart
lib/core/presentation/pages/auth/login_page.dart
lib/core/presentation/pages/edit_profile/edit_profile_page.dart
lib/core/presentation/pages/edit_profile/sub_pages/edit_profile_personal_page.dart
lib/core/presentation/pages/edit_profile/widgets/edit_profile_avatar.dart
lib/core/presentation/pages/onboarding/sub_page/onboarding_about_page.dart
lib/core/presentation/pages/onboarding/sub_page/onboarding_profile_photo_page.dart
lib/core/presentation/pages/onboarding/sub_page/onboarding_username_page.dart
lib/core/presentation/pages/profile/widgets/profile_page_header_widget.dart
lib/core/presentation/widgets/common/button/linear_gradient_button_widget.dart
lib/core/presentation/widgets/common/dropdown/frosted_glass_drop_down_v2.dart
lib/core/presentation/widgets/lemon_bottom_sheet_mixin.dart
lib/core/presentation/widgets/lemon_text_field.dart
lib/i18n/common/common_en.i18n.json
lib/i18n/profile/profile_en.i18n.json
lib/theme/color.dart

- Add integration with GraphQL on Edit profile screen.
- Add progress indicator on linear gradient button
- **Note**: Date of Birth edit is NOT implemented. I'm requesting design to simplify it to match with web version.
https://github.com/lemonadesocial/lemonade-flutter/assets/108661349/3533302f-467e-492f-bd6e-23dfb3e8603d

Feat/ Edit profile graphQL integration

---

lib/core/presentation/widgets/bottom_bar/bottom_bar_widget.dart

- Issue trello: https://trello.com/c/ZhjbvDxl/219-adjust-double-tap-scrolltotop-to-single-tap-scrolltotop-in-newsfeed-page

fix(home screen): Quick fix home screen scroll behavior

---

lib/core/application/poap/claim_poap_bloc/claim_poap_bloc.dart
lib/core/application/poap/poap_claim_subscription_bloc/poap_claim_subscription_bloc.dart
lib/core/data/event/dtos/event_dtos.dart
lib/core/data/event/event_query.dart
lib/core/data/poap/poap_repository_impl.dart
lib/core/data/token/dtos/token_dtos.dart
lib/core/data/token/token_query.dart
lib/core/data/token/token_repository_impl.dart
lib/core/domain/event/entities/event.dart
lib/core/domain/event/event_enums.dart
lib/core/domain/poap/poap_repository.dart
lib/core/domain/token/entities/token_entities.dart
lib/core/domain/token/input/get_tokens_input.dart
lib/core/domain/token/token_repository.dart
lib/core/presentation/pages/event/events_listing_page.dart
lib/core/presentation/pages/event/guest_event_detail_page/views/post_guest_event_detail_view.dart
lib/core/presentation/pages/event/guest_event_detail_page/widgets/guest_event_poap_offer_item.dart
lib/core/presentation/pages/event/guest_event_detail_page/widgets/guest_event_poap_offers.dart
lib/core/presentation/pages/poap/popap_detail_page.dart
lib/core/presentation/widgets/common/button/lemon_outline_button_widget.dart
lib/core/presentation/widgets/poap/poap_item.dart
lib/core/presentation/widgets/poap/poap_quantity_bar.dart
lib/core/utils/event_utils.dart

- show guest event poap offers 
- claim event poap offers
https://github.com/lemonadesocial/lemonade-flutter/assets/28992487/58eb7df8-59f7-403c-a89d-ecf92e33723a
https://github.com/lemonadesocial/lemonade-flutter/assets/28992487/1c7a37c2-60a8-436e-ad62-fc4efc284b45

feat(event offers): implement show event poap offer and claim

---

lib/core/presentation/pages/chat/chat_message/view/chat_message_view.dart
lib/core/presentation/pages/chat/chat_message/widgets/chat_settings_popup_menu.dart
lib/i18n/chat/chat_en.i18n.json
lib/i18n/common/common_en.i18n.json
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

feat(chat): implement leave chat

---

lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_ticket_management_page/widgets/ticket_assign_popup.dart
lib/i18n/event/event_en.i18n.json

- Implement assign ticket popup ui

feat(event assign): implement assign tickets popup ui

---

.github/workflows/commit_lint.yml
lib/core/presentation/pages/discover/discover_page/views/discover_cards.dart
lib/core/presentation/widgets/discover/discover_card.dart
lib/core/service/wallet_connect/wallet_connect_service.dart
lib/i18n/discover/discover_en.i18n.json

- Update discover cards layout (remove vinyls card, fit other 3 cards in 1 row like in figma)

Feat/polish UI discover

---

ios/Podfile.lock
pubspec.lock
pubspec.yaml

- Fix iOS build by adjust firebase version

chore: adjust firebase version

---

lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_ticket_management_page/widgets/my_ticket_card.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/select_tickets_page/widgets/select_ticket_item.dart
lib/router/app_router.dart
pubspec.lock
pubspec.yaml

- Generate QR code for event ticket

feat(event tickets): add qr code lib for event tickets

---

lib/core/presentation/widgets/home/create_pop_up_page.dart
lib/core/presentation/widgets/home/create_pop_up_tile.dart
lib/theme/color.dart
pubspec.lock

- Add gradient color for buttons

feat(create post): add gradient color for buttons

---

lib/app.dart
lib/core/presentation/widgets/common/button/linear_gradient_button_widget.dart
lib/core/presentation/widgets/custom_error_widget.dart
lib/i18n/common/common_en.i18n.json

Right now if something wrong happen in app (Crashed or some wrong data problem), it's will causing white/gray screen, so we need global way to handle that
Using ErrorBuilder to build custom UI when something wrong happen

feat: implement global error widget

---

codemagic.yaml

- Enhance ci/cd to not submit PlayStore as draft

ci: enhance ci/cd to not submit playstore as draft

---

ios/Podfile.lock
lib/app.dart
lib/core/application/auth/auth_bloc.dart
lib/core/data/user/dtos/user_query.dart
lib/core/oauth/oauth.dart
lib/core/presentation/pages/setting/setting_page.dart
lib/core/presentation/pages/setting/widgets/setting_delete_account_dialog.dart
lib/core/service/auth/auth_service.dart
lib/i18n/setting/setting_en.i18n.json
pubspec.yaml

feat(delete account): implement delete account feature

---

lib/core/presentation/pages/event/my_event_ticket_page/my_event_ticket_page.dart
lib/core/presentation/pages/event/my_event_ticket_page/widgets/ticket_actions.dart
lib/core/presentation/pages/event/my_event_ticket_page/widgets/ticket_qr_code_popup.dart
lib/core/presentation/pages/event/my_event_ticket_page/widgets/tickets_cost_summary.dart
lib/i18n/event/event_en.i18n.json
lib/theme/color.dart
pubspec.lock

- Add cost summary and show qr code popup in ticket page

feat(event ticket): enhance my ticket page

---

lib/core/presentation/pages/home/home_page.dart
lib/core/presentation/pages/root/root_page.dart
lib/core/utils/swipe_detector.dart
lib/injection/register_module.config.dart

- Implement swipe left to open chat

feat: Swipe left to open chat

---

lib/core/presentation/pages/discover/discover_page/discover_page.dart
lib/core/presentation/pages/notification/notifications_listing_page.dart
lib/core/presentation/pages/profile/profile_page.dart
lib/core/presentation/pages/profile/views/profile_page_view.dart

- Add swipe left chat to every screen

feat: add swipe left chat to every screen

---

codemagic.yaml

- Remove auto trigger build flow

chore: remove triggering in ci/cd flow

---

lib/core/data/notification/notification_constants.dart
lib/core/domain/notification/entities/notification.dart
lib/core/presentation/pages/notification/notifications_listing_page.dart
lib/core/presentation/pages/notification/widgets/notification_card_widget.dart
lib/core/utils/navigation_utils.dart

- Handle navigation when on on notification item

fix: handle navigation when on on notification item

---

lib/core/presentation/pages/discover/discover_page/views/discover_upcoming_events.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_ticket_management_page/event_ticket_management_page.dart

- Fix wrong navigation for upcoming events in discover page

fix: wrong upcoming event navigation

---

lib/app.dart
lib/core/application/event_tickets/buy_tickets_with_crypto_bloc/buy_tickets_with_crypto_bloc.dart
lib/core/constants/web3/chains.dart
lib/core/data/web3/dtos/chain_dto.dart
lib/core/data/web3/web3_query.dart
lib/core/data/web3/web3_repository_impl.dart
lib/core/domain/web3/entities/chain.dart
lib/core/domain/web3/web3_repository.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/select_tickets_page/select_tickets_page.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/select_tickets_page/widgets/other_ticket_item.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/select_tickets_page/widgets/select_ticket_item.dart
lib/core/presentation/widgets/web3/chain/chain_query_widget.dart
lib/injection/register_module.config.dart

- Use chains data from server instead of hard-coding
- Handle send transaction for native token

feat(payment): dynamic chain list, transaction for native token

---

lib/core/application/ai/get_ai_config_bloc/get_ai_config_bloc.dart
lib/core/config.dart
lib/core/data/ai/dtos/ai_dtos.dart
lib/core/data/ai/query/ai_query.dart
lib/core/data/ai/repository/ai_repository_impl.dart
lib/core/domain/ai/ai_entities.dart
lib/core/domain/ai/ai_repository.dart
lib/core/domain/ai/input/get_ai_config_input/get_ai_config_input.dart
lib/core/presentation/pages/ai/ai_page.dart
lib/core/presentation/pages/ai/widgets/ai_chat_command_view.dart
lib/core/presentation/pages/root/root_page.dart
lib/core/presentation/widgets/ai/ai_chat_card.dart
lib/core/presentation/widgets/ai/ai_chat_composer.dart
lib/core/presentation/widgets/ai/ai_chat_default_grid.dart
lib/core/presentation/widgets/common/drawer/lemon_drawer.dart
lib/core/presentation/widgets/common/list_tile/custom_list_tile.dart
lib/core/utils/gql/gql.dart
lib/graphql/config.graphql
lib/graphql/config_fragment.graphql
lib/injection/register_module.config.dart

- Update to use other ai config
- Cancel subscription when unmount widget

fix(ai-chat): update chat ai patch

---

lib/core/application/event/create_event_bloc/create_event_bloc.dart
lib/core/application/event/event_location_setting_bloc/event_location_setting_bloc.dart
lib/core/domain/event/entities/event_configuration.dart
lib/core/presentation/pages/event/create_event/sub_pages/create_event_base_page.dart
lib/core/presentation/pages/event/create_event/widgets/create_event_config_grid.dart
lib/core/presentation/pages/event/create_event/widgets/event_config_card.dart
lib/core/presentation/pages/event/event_location_setting_page/event_location_setting_page.dart
lib/core/presentation/pages/event/event_location_setting_page/widgets/location_item.dart
lib/i18n/event/event_en.i18n.json
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

- Provide edit virtual when create event
- Can attached location into event creation flow

feat: attached virtual and location to event creation flow

---

lib/core/config.dart
lib/core/data/crypto_ramp/crypto_ramp_repository_impl.dart
lib/core/data/crypto_ramp/stripe_onramp/dtos/stripe_onramp_session_dto/stripe_onramp_session_dto.dart
lib/core/data/crypto_ramp/stripe_onramp/mutation/stripe_onramp_mutation.dart
lib/core/domain/crypto_ramp/crypto_ramp_repository.dart
lib/core/domain/crypto_ramp/stripe_onramp/entities/stripe_onramp_session/stripe_onramp_session.dart
lib/core/domain/crypto_ramp/stripe_onramp/input/create_stripe_onramp_session_input/create_stripe_onramp_session_input.dart
lib/core/presentation/pages/cryto-ramp/stripe_onramp/stripe_onramp_webview.dart
lib/injection/register_module.config.dart

- Create Stripe onramp session
- Create Webview to display onramp UI from Stripe Web SDK

feat(crypto ramp) create stripe onramp session

---

lib/core/presentation/pages/cryto-ramp/stripe_onramp/stripe_onramp_webview.dart

- pass client secret and public key to webview using query param

fix(stripe onramp): fix onramp webview

---

lib/core/presentation/pages/cryto-ramp/stripe_onramp/stripe_onramp_webview.dart
lib/core/presentation/pages/vault/create_vault_page/sub_pages/create_vault_submit_transaction_page/view/deploy_vault_with_owner_key_view.dart
lib/core/presentation/pages/vault/create_vault_page/sub_pages/create_vault_submit_transaction_page/widgets/owner_key_balance_widget.dart

- Fix stripe onramp webview not redirect due to parse data error 
- Remove prepopulating topup amount
- Add error message when network is not supported on stripe onramp

fix: onramp webview not redirect, remove prepopulate topup amount

---

lib/core/application/event/get_event_checkins_bloc/get_event_checkins_bloc.dart
lib/core/application/event/update_event_checkin_bloc/update_event_checkin_bloc.dart
lib/core/data/event/repository/event_repository_impl.dart
lib/core/domain/event/entities/event_checkin.dart
lib/core/domain/event/event_repository.dart
lib/core/presentation/pages/event/event_detail_page/event_detail_page.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/view/host_event_detail_view.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/widgets/host_actions_bar.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/widgets/host_event_detail_config_grid.dart
lib/core/presentation/pages/scan_qr_code/scan_qr_code_page.dart
lib/core/presentation/pages/scan_qr_code/widgets/scanner_error_widget.dart
lib/graphql/backend/event/mutation/update_event_checkin.graphql
lib/graphql/backend/event/query/get_event_checkins.graphql
lib/i18n/event/event_en.i18n.json
lib/router/app_router.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

- Event checkin flow
https://github.com/lemonadesocial/lemonade-flutter/assets/7247063/e7b4dfc0-cd80-4ef5-ad3a-27063c572b6a

feat: event checkin

---

.github/workflows/release_please.yml
codemagic.yaml

- Add release-please
- Remove automate create release in Codemagic script

ci: add release please

---

.github/workflows/release_please.yml
android/app/src/main/AndroidManifest.xml

- Add camera permission android
- Update branch triggering

chore: add camera permission android

---

lib/core/application/event_tickets/select_event_tickets_bloc/select_event_tickets_bloc.dart

- Remove condition disabled redeem button

fix: remove condition disabled redeem button

---

lib/core/application/vault/create_vault_owner_key_bloc/create_vault_owner_key_bloc.dart
lib/core/presentation/pages/vault/create_vault_page/sub_pages/create_vault_setup_phrase_page/create_vault_setup_phrase_page.dart
lib/core/service/vault/private_key/private_key.dart

- fix: use compute when generating seed from mnemonic

fix: use compute when generating seed from mnemonic

---

codemagic.yaml

- fix codemagic scripts syntax

chore: fix codemagic scripts syntax

---

lib/core/presentation/pages/onboarding/sub_page/onboarding_term_condition_page.dart

- Enable accept term button by default in onboarding flow

fix: enable accept term button by default in onboarding flow

---

appcast.xml

chore: increase force version check to 1.1.4

---

lib/core/presentation/pages/root/root_page.dart
lib/core/presentation/pages/setting/setting_page.dart

- Disabled swipe drawer if unauthenticated
- Remove coming soon label of vaults item in setting page

fix: disable swipe drawer if unauthenticated

---

lib/core/domain/event/entities/event_configuration.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_control_panel_base_page/event_control_panel_base_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_control_panel_base_page/widgets/event_tickets_grid_config.dart
lib/i18n/event/event_en.i18n.json
lib/router/app_router.dart

- Fix existing issue can't navigate to "Ticket Tiers" page due to wrong resolved conflict by me
- Add new configuration settings call "Tickets" to include "Ticket Tiers" & "Promotions"

feat: add tickets control settings

---

lib/core/application/event_tickets/modify_ticket_price_bloc/modify_ticket_price_bloc.dart
lib/core/application/event_tickets/modify_ticket_type_bloc/modify_ticket_type_bloc.dart
lib/core/application/payment/connect_payment_account_bloc/connect_payment_account_bloc.dart
lib/core/data/event/dtos/event_dtos.dart
lib/core/data/event/repository/event_ticket_repository_impl.dart
lib/core/domain/event/entities/event.dart
lib/core/domain/event/input/ticket_type_input/ticket_type_input.dart
lib/core/domain/event/repository/event_ticket_repository.dart
lib/core/domain/form/string_formz.dart
lib/core/domain/payment/input/create_payment_account_input/create_payment_account_input.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_control_panel_base_page/widgets/event_collaborations_grid_config.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/event_create_ticket_tier_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/widgets/add_ticket_tier_pricing_form.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/widgets/create_ticket_basic_info_form.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/widgets/create_ticket_guest_form.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/widgets/create_ticket_pricing_form.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/widgets/get_chains_list_builder.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/widgets/get_event_currencies_builder.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/widgets/ticket_tier_pricing_item.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_ticket_tiers_listing_page/widgets/payout_accounts_widget.dart
lib/core/presentation/widgets/common/bottomsheet/lemon_snap_bottom_sheet_widget.dart
lib/core/presentation/widgets/web3/connect_wallet_button.dart
lib/core/utils/event_tickets_utils.dart
lib/core/utils/number_utils.dart
lib/core/utils/web3_utils.dart
lib/graphql/backend/event/fragment/event_ticket_fragment.graphql
lib/i18n/event/event_en.i18n.json
lib/router/app_router.dart
pubspec.lock
pubspec.yaml

- Implement create erc20 payment account 
- Implement create ticket tier (with erc20 prices only) 
- Implement connect with stripe to create Stripe payment account 
- Implement create ticket tier (with fiat prices)

feat: create ticket tier (erc20 prices only)

---

lib/core/application/event_tickets/modify_ticket_type_bloc/modify_ticket_type_bloc.dart
lib/core/data/event/repository/event_ticket_repository_impl.dart
lib/core/domain/event/repository/event_ticket_repository.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/event_create_ticket_tier_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/widgets/create_ticket_basic_info_form.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/widgets/create_ticket_guest_form.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/widgets/ticket_tier_pricing_item.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_ticket_tiers_listing_page/event_ticket_tiers_listing_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_ticket_tiers_listing_page/widgets/ticket_tier_item.dart
lib/core/presentation/pages/vault/create_vault_page/sub_pages/create_vault_submit_transaction_page/widgets/owner_key_balance_widget.dart
lib/core/utils/web3_utils.dart

- Populate ticket tier data to edit 
- Implement api call to update the ticket tier
- Modify ticket tier's price item (will separate into another PR)
https://github.com/lemonadesocial/lemonade-flutter/assets/28992487/18a9ac3e-d408-4eb4-9375-d924e0770da1

feat: edit ticket tier

---

lib/core/application/event_tickets/modify_ticket_type_bloc/modify_ticket_type_bloc.dart
lib/core/data/event/dtos/event_ticket_types_dto/event_ticket_types_dto.dart
lib/core/data/event/gql/event_payment_query.dart
lib/core/data/event/gql/event_query.dart
lib/core/data/event/repository/event_ticket_repository_impl.dart
lib/core/domain/event/entities/event_ticket_types.dart
lib/core/domain/event/repository/event_ticket_repository.dart
lib/core/presentation/dpos/common/dropdown_item_dpo.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/event_create_ticket_tier_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/widgets/ticket_tier_pricing_item.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_ticket_tiers_listing_page/widgets/ticket_tier_item.dart
lib/core/presentation/widgets/floating_frosted_glass_dropdown_widget.dart
lib/core/presentation/widgets/frosted_glass_dropdown_widget.dart
lib/graphql/backend/event/fragment/event_fragment.graphql
lib/graphql/backend/event/fragment/event_ticket_fragment.graphql
lib/graphql/backend/event/mutation/delete_event_ticket_type.graphql
lib/i18n/event/event_en.i18n.json

- Add modify actions (make default, inactivate, delete) for ticket tier 
- Add modify actions (make default, delete) for ticket tier's pricing 
https://github.com/lemonadesocial/lemonade-flutter/assets/28992487/c57b5eab-1011-442f-adfa-719204925ae8

feat: ticket tier modify actions

---

appcast.xml

chore: increase appcast version

---

lib/core/application/event/create_event_bloc/create_event_bloc.dart

- Add published true when create event

fix: add published true when create event

---

lib/core/application/event/event_guest_settings_bloc/event_guest_settings_bloc.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_guest_settings_page/event_guest_settings_page.dart

- fix wrong require approval initial value

chore: fix wrong require approval initial value

---

lib/core/application/event_tickets/buy_tickets_bloc/buy_tickets_bloc.dart
lib/core/application/event_tickets/buy_tickets_with_crypto_bloc/buy_tickets_with_crypto_bloc.dart
lib/core/domain/payment/input/update_payment_input/update_payment_input.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_tickets_summary_page/event_tickets_summary_page.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_tickets_summary_page/handler/wait_for_payment_notification_handler.dart

- Only call buyTickets once
- If pay by stripe or metamask failed, will use the old payment and update again

fix: update buy tickets api call flow

---

lib/core/data/event/dtos/event_join_request_dto/event_join_request_dto.dart
lib/core/data/event/dtos/event_ticket_dto/event_ticket_dto.dart
lib/core/data/event/repository/event_repository_impl.dart
lib/core/domain/event/entities/event_join_request.dart
lib/core/domain/event/entities/event_ticket.dart
lib/core/domain/event/event_repository.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/event_approval_setting_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/view/event_join_requests_list.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/event_join_request_actions_bar.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/event_join_request_item.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/view/host_event_detail_view.dart
lib/graphql/backend/event/fragment/event_join_request_fragment.graphql
lib/graphql/backend/event/mutation/approve_user_join_requests.graphql
lib/graphql/backend/event/mutation/decline_user_join_requests.graphql
lib/graphql/backend/event/query/get_event_join_request.graphql
lib/graphql/backend/schema.graphql
lib/i18n/event/event_en.i18n.json
lib/router/app_router.dart

- Integrate api approve/decline join request
- Integrate api get join requests listing 
- Draft UI for join request list
- Update EventJoinRequest schema

feat: approve/decline join request, join request listing

---

lib/core/data/event/gql/event_join_request_query.dart
lib/core/data/event/gql/event_tickets_mutation.dart

- update buy redeem tickets mutation

fix: update buy redeem tickets mutation

---

lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/event_approval_setting_page.dart

- Fix break layout in approval setting page

fix: fix break layout in approval setting page

---

appcast.xml

- Increase force check update version to 1.3.0

chore: increase force appcast version to 1.3.0

---

lib/core/presentation/pages/post_detail/post_detail_page.dart
lib/core/presentation/pages/post_detail/widgets/post_comment_tile.dart
lib/core/presentation/pages/post_detail/widgets/post_detail_card.dart
lib/core/presentation/widgets/post/post_profile_card_widget.dart
lib/i18n/common/common_en.i18n.json

- https://trello.com/c/LX6bnByy/342-post-comment-post-missing-username

fix: show name in post comments

---

lib/core/data/event/dtos/event_dtos.dart
lib/core/data/event/gql/event_query.dart
lib/core/domain/common/entities/common.dart
lib/core/domain/event/entities/event.dart
lib/core/domain/user/entities/user.dart
lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/widgets/guest_event_detail_buy_button.dart
lib/core/utils/string_utils.dart
lib/graphql/backend/event/fragment/event_fragment.graphql
lib/i18n/event/event_en.i18n.json

- Check profile required fields to be qualified to buy tickets in a event

feat: check profile required fields before buying tickets

---

lib/core/data/event/gql/event_query.dart
lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/widgets/guest_event_detail_buy_button.dart
lib/core/presentation/pages/vault/create_vault_page/sub_pages/create_vault_check_phrase_page/create_vault_check_phrase_page.dart
lib/core/presentation/pages/vault/create_vault_page/sub_pages/create_vault_setup_phrase_page/view/show_recovery_phrase_bottom_sheet.dart
lib/core/presentation/pages/vault/vaults_listing_page/views/add_vault_bottomsheet.dart
lib/core/presentation/widgets/event/event_buy_ticket_button_widget.dart
lib/core/utils/device_utils.dart
lib/core/utils/event_tickets_utils.dart
lib/core/utils/list_utils.dart

- Fix show wrong price on buy ticket button
- Other layout break on in vault creation

fix: fix show wrong ticket price on buy ticket button

---

lib/core/presentation/pages/edit_profile/edit_profile_page.dart
lib/i18n/setting/setting_en.i18n.json

- Update setting's page app bar title
- Add onTap function to navigate to setting page when tap personal card in profile page

fix: update setting page, update profile page

---

lib/core/data/user/dtos/user_dtos.dart
lib/core/domain/user/entities/user.dart
lib/core/presentation/widgets/event/event_post_card_widget.dart

- Fix `new_photos_expanded` breaking in user dto

fix: new photo expanded breaking in user dto

---

lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/widgets/guest_event_detail_hosts.dart
lib/core/presentation/pages/event/widgets/event_card_widget.dart

- Fix event host item avatar crash

fix: event host item avatar crash

---

lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/sub_pages/event_join_request_application_page/widgets/event_join_request_application_user_card.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/event_join_request_ticket_info.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/event_join_request_ticket_info_builder.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/join_request_item/event_pending_join_request_item.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/join_request_item/event_rejected_join_request_item.dart
lib/core/utils/web3_utils.dart
lib/graphql/backend/event/fragment/event_join_request_fragment.graphql

- Show join request's total payment account

fix: show join request total payment amount

---

lib/core/application/event_tickets/buy_tickets_bloc/buy_tickets_bloc.dart
lib/core/application/event_tickets/select_event_tickets_bloc/select_event_tickets_bloc.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_ticket_tier_setting_page/sub_pages/event_create_ticket_tier_page/widgets/ticket_tier_pricing_item.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_tickets_summary_page/event_tickets_summary_page.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_tickets_summary_page/widgets/event_order_slide_to_pay.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_tickets_summary_page/widgets/event_order_summary.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_tickets_summary_page/widgets/event_tickets_summary.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/select_tickets_page/widgets/other_ticket_item.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/select_tickets_page/widgets/other_ticket_types_list.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/select_tickets_page/widgets/select_ticket_item.dart
lib/core/utils/event_tickets_utils.dart
lib/core/utils/payment_utils.dart

- fix: check network null or empty causing wrong detect type of payment (ethereum or stripe)

fix: check network null or empty

---

lib/core/presentation/widgets/poap/poap_claimed_poup/poap_claimed_popup.dart

- Fix layout claim poap success popup

fix: layout claim poap success popup

---

lib/core/data/post/query/post_query.dart

- add query event_ticket_types into ref_event when get newsfeed

fix: add query event_ticket_types into ref_event when get newsfeed

---

lib/core/domain/event/entities/event_accepted_export.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/event_approval_setting_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/view/event_accepted_export_list.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/event_accepted_export_item.dart
lib/graphql/backend/event/fragment/event_accepted_export_fragment.graphql
lib/graphql/backend/schema.graphql

- Enhance guest list ui for auto approve event

chore: enhance guest list ui for auto approve event

---

lib/core/data/event/dtos/event_dtos.dart
lib/core/data/event/gql/event_query.dart
lib/core/domain/event/entities/event.dart
lib/core/presentation/pages/event/event_detail_page/event_detail_base_page.dart
lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/views/post_guest_event_detail_view.dart
lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/widgets/guest_event_detail_basic_info.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/view/host_event_detail_view.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/widgets/host_checkin_guests_action.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/widgets/host_event_basic_info_card.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/widgets/host_event_detail_config_grid.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/widgets/host_event_poap_reward_card.dart
lib/core/utils/event_utils.dart
lib/i18n/event/event_en.i18n.json

- Fix check cohost permission in event detail
- Integrate with `pending_request_count` number display
- Enhance some UI

fix: check cohost permission in event detail

---

lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/event_issue_tickets_setting_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_form_page/event_issue_tickets_form_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_form_page/widgets/issue_tickets_assignment_form.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_form_page/widgets/issue_tickets_dropdown.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_processing_page/event_issue_tickets_proccessing_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_processing_page/view/event_issue_tickets_loading_view.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_processing_page/view/event_issue_tickets_success_view.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_summary_page/event_issue_tickets_summary_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_summary_page/widgets/event_issue_tickets_summary.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/widgets/host_event_detail_config_grid.dart
lib/core/presentation/widgets/animation/success_circle_animation_widget.dart
lib/core/presentation/widgets/common/button/linear_gradient_button_widget.dart
lib/i18n/common/common_en.i18n.json
lib/i18n/event/event_en.i18n.json
lib/router/app_router.dart

- Issues tickets flow UI
- Loading indicator animation is complex so will separate it from this PR

feat: issues tickets flow ui

---

lib/core/application/event_tickets/issue_tickets_bloc/issue_tickets_bloc.dart
lib/core/data/event/dtos/event_ticket_dto/event_ticket_dto.dart
lib/core/data/event/repository/event_ticket_repository_impl.dart
lib/core/domain/event/entities/event_ticket.dart
lib/core/domain/event/repository/event_ticket_repository.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/event_issue_tickets_setting_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_form_page/event_issue_tickets_form_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_form_page/widgets/issue_tickets_assignment_form.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_form_page/widgets/issue_tickets_dropdown.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_processing_page/event_issue_tickets_proccessing_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_processing_page/view/event_issue_tickets_success_view.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_summary_page/event_issue_tickets_summary_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_summary_page/widgets/event_issue_tickets_summary.dart
lib/graphql/backend/event/mutation/create_tickets.graphql

- Integrate api and handle logic issuing tickets by email
- Temporary hide loading view due to complex animation, using showFutureLoading instead
https://github.com/lemonadesocial/lemonade-flutter/assets/28992487/e40f990d-7b67-4ebe-a38b-b2f81df19c65

feat: issues tickets from host to user

---

lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_processing_page/event_issue_tickets_proccessing_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_processing_page/view/event_issue_tickets_loading_view.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_summary_page/event_issue_tickets_summary_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_issue_tickets_setting_page/sub_pages/event_issue_tickets_summary_page/widgets/event_issue_tickets_summary.dart

- Add loading animation when issuing tickets 
https://github.com/lemonadesocial/lemonade-flutter/assets/28992487/fce0f65a-29ac-4708-a55d-e93f1c297a71

feat: add loading animation when issuing tickets

---

lib/core/presentation/pages/chat/chat_message/widgets/message_item/message_item_widget.dart

- Fix show sender avatar in matrix chat

fix: show sender avatar in matrix chat

---

lib/core/data/event/dtos/event_dtos.dart
lib/core/domain/event/entities/event.dart
lib/graphql/backend/event/fragment/event_fragment.graphql
lib/graphql/backend/schema.graphql

- fix event statistics is reset when update event

fix: fix issue event statistics is reset when udpate event

---

lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/widgets/guest_event_location.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/widgets/host_event_basic_info_card.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/widgets/host_event_location.dart
lib/core/presentation/widgets/map/map_option_bottom_sheet.dart
lib/core/utils/map_utils.dart

- Add view map option for event location, 
- fix navigation when press event statistics
https://github.com/lemonadesocial/lemonade-flutter/assets/28992487/8e15e17f-d2f9-46c7-adfa-8529e431b623

fix: add view map option for event location, fix navigation when press event statistics

---

lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/widgets/guest_event_location.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/widgets/host_event_location.dart
lib/core/utils/event_utils.dart

- Fix show wrong event detail address https://trello.com/c/Kj7mRj5A

fix: show wrong event detail address

---

lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_control_panel_base_page/event_control_panel_base_page.dart
lib/graphql/backend/event/fragment/event_fragment.graphql

- Fix event detail not refresh correctly when finish update event detail

fix: fix event detail not refresh correctly when finish update event detail

---

lib/core/application/event_tickets/buy_tickets_bloc/buy_tickets_bloc.dart
lib/core/application/event_tickets/buy_tickets_with_crypto_bloc/buy_tickets_with_crypto_bloc.dart
lib/core/application/event_tickets/calculate_event_tickets_pricing_bloc/calculate_event_tickets_pricing_bloc.dart
lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/views/post_guest_event_detail_view.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/view/host_event_detail_view.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_tickets_summary_page/event_tickets_summary_page.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_tickets_summary_page/widgets/add_promo_code_input.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_tickets_summary_page/widgets/event_order_summary_footer.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_tickets_summary_page/widgets/pay_by_crypto_button.dart
lib/core/utils/text_formatter/upper_case_text_formatter.dart

- Update payment flow for 100% discount code 
- Use uppercase for promo code input

fix: update payment flow for 100% discount code

---

android/app/src/main/AndroidManifest.xml
ios/Podfile.lock
ios/Runner/Info.plist
ios/Runner/Runner.entitlements
lib/router/app_router.dart

In-Progress
iOS
https://github.com/lemonadesocial/lemonade-flutter/assets/7247063/ebc7e8c8-254c-4d0a-bf3c-3c8e79b30521
Android 
https://github.com/lemonadesocial/lemonade-flutter/assets/7247063/84daf62e-fbd9-4095-97ea-e0ba69184da8

feat: configure universal links

---

ios/Podfile.lock
lib/core/presentation/pages/ai/widgets/ai_chat_command_view.dart
lib/core/presentation/pages/event/events_listing_page.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_ticket_management_page/event_ticket_management_page.dart
lib/core/presentation/widgets/common/drawer/lemon_drawer.dart
lib/core/presentation/widgets/common/drawer/widgets/lemon_drawer_tile_widget.dart
lib/i18n/event/event_en.i18n.json

- Add My Events shortcut to app drawer
- Fix navigation when pick tickets

fix: add my events shortcut to app drawer

---

lib/core/application/event/invite_event_bloc/invite_event_bloc.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/event_approval_setting_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/view/event_accepted_export_list.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/view/event_checkins_list.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/view/event_invited_list.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/event_invited_item.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_invite_setting_page/event_invite_setting_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_invite_setting_page/sub_pages/event_invite_form_page/event_invite_form_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_invite_setting_page/sub_pages/event_invite_form_page/widgets/event_invite_form.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_invite_setting_page/sub_pages/event_invite_processing_page/event_invite_proccessing_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_invite_setting_page/sub_pages/event_invite_processing_page/view/event_invite_loading_view.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_invite_setting_page/sub_pages/event_invite_processing_page/view/event_invite_success_view.dart
lib/graphql/backend/event/mutation/invite_event.graphql
lib/i18n/event/event_en.i18n.json
lib/router/app_router.dart

- Invite guest to event feature
https://github.com/lemonadesocial/lemonade-flutter/assets/28992487/f58605d1-dc8e-474d-9270-8f16a769b88e

feat: invite event

---

lib/core/presentation/pages/auth/login_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_invite_setting_page/sub_pages/event_invite_processing_page/event_invite_proccessing_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_invite_setting_page/sub_pages/event_invite_processing_page/view/event_invite_loading_view.dart

- Fix invited count not updated after invite guest

fix: fix invited count not updated after invite guest

---

lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/event_approval_setting_page.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/widgets/host_event_basic_info_card.dart

- Update navigation logic for guests tab in host event view

fix: update navigation logic for guests tab in host event view

---

lib/core/presentation/pages/profile/views/tabs/profile_event_tab_view.dart
lib/core/presentation/widgets/common/badge/username_badge_widget.dart

fix: update user profile ui

---

lib/core/presentation/pages/setting/setting_page.dart
lib/core/presentation/widgets/common/drawer/lemon_drawer.dart

- Fix pop setting page after logout

fix: pop setting page after logout

---

lib/app.dart
lib/core/presentation/pages/root/root_page.dart
lib/core/utils/gql/custom_error_handler.dart
lib/core/utils/snackbar_utils.dart
pubspec.lock
pubspec.yaml

- Update snackbar to top using another_flusbar library
https://github.com/lemonadesocial/lemonade-flutter/assets/28992487/8b59162d-7b5a-4807-b9b7-f3cd2ab80547

fix: update snackbar to top using another_flushbar library

---

lib/app.dart
lib/core/presentation/pages/root/root_page.dart
lib/core/utils/snackbar_utils.dart
pubspec.lock
pubspec.yaml

- Revert back to use built-in snack bar because flushbar now conflicts with navigator system

fix: revert using built in snackbar due to conflict with navigator

---

assets/icons/ic_approval_approved.svg
assets/icons/ic_approval_declined.svg
assets/icons/ic_approval_pending.svg
lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/sub_pages/guest_event_approval_status_page/guest_event_approval_status_page.dart
lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/widgets/guest_event_detail_buy_button.dart
lib/i18n/event/event_en.i18n.json
lib/router/app_router.dart
pubspec.lock
pubspec.yaml

- Event approval status view for guest
https://github.com/lemonadesocial/lemonade-flutter/assets/28992487/02141f53-0ebc-45a3-9dc9-3747a10bb4ab

feat: event approval status for guest view

---

lib/core/data/event/gql/event_tickets_query.dart
lib/core/data/payment/dtos/escrow_deposit_info_dto/escrow_deposit_info_dto.dart
lib/core/data/payment/payment_query.dart
lib/core/domain/payment/entities/escrow_deposit_info/escrow_deposit_info.dart
lib/graphql/backend/schema.graphql

- Adapt breaking change in ticket pricing info

fix: adapt calculate ticket pricing info breaking changes

---

lib/core/data/event/dtos/redeem_tickets_response_dto/redeem_tickets_response_dto.dart
lib/core/domain/event/entities/redeem_tickets_response.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/event_buy_tickets_page.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_buy_tickets_processing_page/event_buy_tickets_processing_page.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/select_tickets_page/select_tickets_page.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/select_tickets_page/widgets/select_ticket_submit_button.dart
lib/core/presentation/widgets/event/rsvp_event_success_popup_widget.dart
lib/graphql/backend/tickets/mutation/redeem_tickets.graphql

- Allow redeem free ticket in case event does not have payment account setup yet

fix: allow redeem free ticket without payment acc setup

---

lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_datetime_settings_page/widgets/event_datetime_setting_row_item.dart
lib/core/presentation/pages/event/sub_events_listing_page/sub_events_listing_page.dart

- Change first day of week of calendar date picker

fix: change first day of week of calendar date picker

---

lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_tickets_summary_page/widgets/rsvp_application_form/widgets/rsvp_application_multi_options_question.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/event_tickets_summary_page/widgets/rsvp_application_form/widgets/rsvp_application_single_option_question.dart
lib/core/presentation/pages/event_tickets/event_buy_tickets_page/sub_pages/select_tickets_page/widgets/select_ticket_item.dart
lib/i18n/common/common_en.i18n.json

- Guest side MCQ polishment 
https://trello.com/c/5UHreddq/802-guest-side-mcq

fix: guest side mcq polishment

---

lib/core/presentation/pages/collaborator/collaborator_discover/widgets/collaborator_discover_activity_section.dart
lib/core/presentation/pages/collaborator/collaborator_discover/widgets/collaborator_discover_basic_info_section.dart
lib/core/presentation/pages/collaborator/collaborator_discover/widgets/collaborator_discover_expertise_offering_card.dart
lib/core/presentation/pages/collaborator/collaborator_discover/widgets/collaborator_discover_icebreakers_section.dart
lib/core/presentation/pages/collaborator/collaborator_discover/widgets/collaborator_discover_photos_card.dart
lib/core/presentation/pages/collaborator/collaborator_discover/widgets/collaborator_discover_social_grid_section.dart
lib/core/presentation/pages/collaborator/collaborator_discover/widgets/collaborator_discover_spotlight_events_section.dart
lib/core/presentation/pages/collaborator/sub_pages/collaborator_edit_profile_page/widgets/collaborator_edit_icebreaker/collaborator_edit_icebreaker.dart
lib/core/presentation/pages/collaborator/sub_pages/collaborator_edit_profile_page/widgets/collaborator_edit_icebreaker/widgets/collaborator_add_icebreaker_answer_bottomsheet.dart
lib/core/presentation/pages/collaborator/sub_pages/collaborator_edit_profile_page/widgets/collaborator_edit_icebreaker/widgets/collaborator_select_icebreaker_prompt_bottomsheet.dart
lib/core/presentation/pages/collaborator/sub_pages/collaborator_edit_profile_page/widgets/collaborator_edit_profile_field_card.dart
lib/core/presentation/pages/collaborator/sub_pages/collaborator_edit_profile_page/widgets/collaborator_edit_social_connect/collaborator_edit_social_connect.dart
lib/core/presentation/pages/collaborator/sub_pages/collaborator_edit_profile_page/widgets/collaborator_edit_spotlight_events/collaborator_edit_spotlight_events.dart
lib/core/presentation/pages/collaborator/sub_pages/collaborator_edit_profile_page/widgets/remove_icon_wrapper.dart
lib/core/presentation/pages/collaborator/sub_pages/collaborator_preview_profile_page/collaborator_preview_profile_page.dart
lib/core/presentation/pages/collaborator/sub_pages/widgets/collaborator_filter_bottomsheet/collaborator_filter_bottomsheet.dart
lib/core/presentation/pages/collaborator/sub_pages/widgets/collaborator_send_like_bottomsheet/collaborator_send_like_bottomsheet.dart
lib/core/presentation/pages/collaborator/sub_pages/widgets/collaborator_user_bottomsheet_header/collaborator_user_bottomsheet_header.dart
lib/core/presentation/pages/event/my_events_page/widgets/my_events_filter_dropdown.dart
lib/core/presentation/pages/event/select_event_page/widgets/select_event_item.dart

https://trello.com/c/TYCGirJO/993-ui-issue-on-swipe-and-match-and-sort-modal-in-the-my-event-page
- Replaced hardcoded color values with theme-based colors in various collaborator sections, including collaborator discover, collaborator  edit profile, and  select event pages.

fix: update UI components to use app theme colors in collaborators

---

lib/app.dart
lib/core/config.dart
lib/core/presentation/pages/collaborator/collaborator_discover/collaborator_discover_page.dart
lib/core/presentation/pages/collaborator/sub_pages/collaborator_like_preview_page/collaborator_like_preview_page.dart
lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/sub_pages/guest_event_guest_directory_page/widgets/guest_directory_item.dart
lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/sub_pages/guest_event_stories_page/guest_event_stories_page.dart
lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/widgets/guest_event_detail_dashboard.dart
lib/core/presentation/pages/event/event_detail_page/guest_event_detail_page/widgets/guest_event_detail_hosts.dart
lib/core/presentation/pages/event/event_detail_page/host_event_detail_page/widgets/host_event_detail_config_grid.dart
lib/core/presentation/pages/event/events_listing_page.dart
lib/core/presentation/pages/home/home_page.dart
lib/core/presentation/pages/notification/notifications_listing_page.dart
lib/core/presentation/pages/root/root_page.dart
lib/core/presentation/widgets/bottom_bar/app_tabs.dart
lib/core/presentation/widgets/bottom_bar/bottom_bar_widget.dart
lib/core/presentation/widgets/home_appbar/home_appbar.dart
lib/main_development.dart
lib/main_production.dart
lib/main_staging.dart
lib/router/app_router.dart

fix: revert hide chat

---

lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/sub_pages/event_join_request_application_page/event_join_request_application_page.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/sub_pages/event_join_request_application_page/widgets/event_join_request_application_user_card.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/event_accepted_export_item.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/event_checkin_item.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/event_invited_item.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/event_join_request_actions_bar.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/join_request_item/event_confirmed_join_request_item.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/join_request_item/event_pending_join_request_item.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/join_request_item/event_rejected_join_request_item.dart
lib/core/presentation/pages/event/event_control_panel_page/sub_pages/event_approval_setting_page/widgets/join_request_user_avatar.dart
lib/core/presentation/pages/event/event_guest_detail_page/widgets/event_guest_detail_actions_bar.dart

- fix UI in approval settings page

fix: fix UI in approval settings page

---

lib/core/presentation/pages/lens/widget/lens_account_lemonade_username/lens_account_lemaonde_username.dart
lib/core/service/wallet/wallet_connect_service.dart
lib/i18n/home/home_en.i18n.json

- Simplified the LensAccountLemonadeUsername widget by removing unnecessary lines and improving readability.
- Updated the wallet connect service to use 'eth_signTypedData_v4' method for better compatibility.

fix: Updated the wallet connect service to use 'eth_signTypedData_v4' method for better compatibility.

---

lib/core/presentation/pages/event/create_event/sub_pages/event_description_field_page.dart
lib/core/presentation/pages/event/event_guest_detail_page/widgets/event_guest_detail_application_questions.dart
lib/core/presentation/pages/event/event_guest_detail_page/widgets/event_guest_detail_ticket_widget.dart
lib/core/presentation/pages/event/event_guest_detail_page/widgets/event_guest_detail_user_info_widget.dart

What ?
- https://trello.com/c/0eDL3c0M/915-eth-address-missing-in-guest-details
- https://trello.com/c/cL3cS3hC/857-description-field-gets-cut-off

Fix: pending bugs

---

lib/core/application/auth/auth_bloc.dart
lib/core/application/notification/watch_notifications_bloc/watch_notification_bloc.dart
lib/core/config.dart
lib/core/presentation/pages/auth/login_page.dart
lib/core/presentation/pages/root/root_page.dart
lib/core/presentation/widgets/ory_wallet_auth/ory_wallet_auth_button.dart
lib/core/service/auth_method_tracker/auth_method_tracker.dart
lib/core/service/event_pass_service/event_pass_service.dart
lib/core/service/ory_auth/ory_auth.dart
lib/core/service/ory_with_wallet_auth/ory_with_wallet_auth.dart
lib/core/utils/gql/custom_error_handler.dart
lib/core/utils/gql/gql.dart
lib/i18n/auth/auth_en.i18n.json
lib/injection/register_module.config.dart
lib/main_development.dart
lib/main_production.dart
lib/main_staging.dart
pubspec.lock
pubspec.yaml

- Login with wallet using ory kratos

feat: login with wallet

---

lib/core/service/wallet/wallet_connect_service.dart
lib/core/utils/lens_utils.dart

- Removed unnecessary lens network condition when connecting to wallet.
- Updated close method to explicitly define return type.
- Simplified chain selection logic in switchChain method.
- Introduced _getChainFromChainId method for better chain handling.
- Added native token details for Lens Mainnet and Testnet in LensUtils.

fix: improve WalletConnectService and LensUtils
